/*
 * Spanel.java
 *
 * Created on 18 de junio de 2010, 11:05 PM
 */

package sudoku;

/**
 *
 * @author  DarioF
 */
public class Spanel extends javax.swing.JFrame {
    
    /** Creates new form Spanel */
    public Spanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf11 = new javax.swing.JTextField();
        tf12 = new javax.swing.JTextField();
        tf13 = new javax.swing.JTextField();
        tf21 = new javax.swing.JTextField();
        tf22 = new javax.swing.JTextField();
        tf23 = new javax.swing.JTextField();
        tf31 = new javax.swing.JTextField();
        tf32 = new javax.swing.JTextField();
        tf33 = new javax.swing.JTextField();
        tf14 = new javax.swing.JTextField();
        tf15 = new javax.swing.JTextField();
        tf16 = new javax.swing.JTextField();
        tf24 = new javax.swing.JTextField();
        tf25 = new javax.swing.JTextField();
        tf26 = new javax.swing.JTextField();
        tf34 = new javax.swing.JTextField();
        tf35 = new javax.swing.JTextField();
        tf36 = new javax.swing.JTextField();
        tf17 = new javax.swing.JTextField();
        tf18 = new javax.swing.JTextField();
        tf19 = new javax.swing.JTextField();
        tf27 = new javax.swing.JTextField();
        tf28 = new javax.swing.JTextField();
        tf29 = new javax.swing.JTextField();
        tf37 = new javax.swing.JTextField();
        tf38 = new javax.swing.JTextField();
        tf39 = new javax.swing.JTextField();
        tf41 = new javax.swing.JTextField();
        tf42 = new javax.swing.JTextField();
        tf43 = new javax.swing.JTextField();
        tf44 = new javax.swing.JTextField();
        tf45 = new javax.swing.JTextField();
        tf46 = new javax.swing.JTextField();
        tf47 = new javax.swing.JTextField();
        tf48 = new javax.swing.JTextField();
        tf49 = new javax.swing.JTextField();
        tf51 = new javax.swing.JTextField();
        tf52 = new javax.swing.JTextField();
        tf53 = new javax.swing.JTextField();
        tf54 = new javax.swing.JTextField();
        tf55 = new javax.swing.JTextField();
        tf56 = new javax.swing.JTextField();
        tf57 = new javax.swing.JTextField();
        tf58 = new javax.swing.JTextField();
        tf59 = new javax.swing.JTextField();
        tf61 = new javax.swing.JTextField();
        tf62 = new javax.swing.JTextField();
        tf63 = new javax.swing.JTextField();
        tf64 = new javax.swing.JTextField();
        tf65 = new javax.swing.JTextField();
        tf66 = new javax.swing.JTextField();
        tf67 = new javax.swing.JTextField();
        tf68 = new javax.swing.JTextField();
        tf69 = new javax.swing.JTextField();
        tf71 = new javax.swing.JTextField();
        tf72 = new javax.swing.JTextField();
        tf73 = new javax.swing.JTextField();
        tf74 = new javax.swing.JTextField();
        tf75 = new javax.swing.JTextField();
        tf76 = new javax.swing.JTextField();
        tf77 = new javax.swing.JTextField();
        tf78 = new javax.swing.JTextField();
        tf79 = new javax.swing.JTextField();
        tf81 = new javax.swing.JTextField();
        tf82 = new javax.swing.JTextField();
        tf83 = new javax.swing.JTextField();
        tf84 = new javax.swing.JTextField();
        tf85 = new javax.swing.JTextField();
        tf86 = new javax.swing.JTextField();
        tf87 = new javax.swing.JTextField();
        tf88 = new javax.swing.JTextField();
        tf89 = new javax.swing.JTextField();
        tf91 = new javax.swing.JTextField();
        tf92 = new javax.swing.JTextField();
        tf93 = new javax.swing.JTextField();
        tf94 = new javax.swing.JTextField();
        tf95 = new javax.swing.JTextField();
        tf96 = new javax.swing.JTextField();
        tf97 = new javax.swing.JTextField();
        tf98 = new javax.swing.JTextField();
        tf99 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tf11.setBackground(new java.awt.Color(51, 51, 255));
        tf11.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf11.setText(" ");

        tf12.setBackground(new java.awt.Color(51, 51, 255));
        tf12.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf12.setText(" ");

        tf13.setBackground(new java.awt.Color(51, 51, 255));
        tf13.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf13.setText(" ");

        tf21.setBackground(new java.awt.Color(51, 51, 255));
        tf21.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf21.setText(" ");

        tf22.setBackground(new java.awt.Color(51, 51, 255));
        tf22.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf22.setText(" ");

        tf23.setBackground(new java.awt.Color(51, 51, 255));
        tf23.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf23.setText(" ");

        tf31.setBackground(new java.awt.Color(51, 51, 255));
        tf31.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf31.setText(" ");

        tf32.setBackground(new java.awt.Color(51, 51, 255));
        tf32.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf32.setText(" ");

        tf33.setBackground(new java.awt.Color(51, 51, 255));
        tf33.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf33.setText(" ");

        tf14.setBackground(new java.awt.Color(102, 255, 102));
        tf14.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf14.setText(" ");

        tf15.setBackground(new java.awt.Color(102, 255, 102));
        tf15.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf15.setText(" ");

        tf16.setBackground(new java.awt.Color(102, 255, 102));
        tf16.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf16.setText(" ");

        tf24.setBackground(new java.awt.Color(102, 255, 102));
        tf24.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf24.setText(" ");

        tf25.setBackground(new java.awt.Color(102, 255, 102));
        tf25.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf25.setText(" ");

        tf26.setBackground(new java.awt.Color(102, 255, 102));
        tf26.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf26.setText(" ");

        tf34.setBackground(new java.awt.Color(102, 255, 102));
        tf34.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf34.setText(" ");

        tf35.setBackground(new java.awt.Color(102, 255, 102));
        tf35.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf35.setText(" ");

        tf36.setBackground(new java.awt.Color(102, 255, 102));
        tf36.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf36.setText(" ");

        tf17.setBackground(new java.awt.Color(255, 102, 153));
        tf17.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf17.setText(" ");

        tf18.setBackground(new java.awt.Color(255, 102, 153));
        tf18.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf18.setText(" ");

        tf19.setBackground(new java.awt.Color(255, 102, 153));
        tf19.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf19.setText(" ");

        tf27.setBackground(new java.awt.Color(255, 102, 153));
        tf27.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf27.setText(" ");

        tf28.setBackground(new java.awt.Color(255, 102, 153));
        tf28.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf28.setText(" ");

        tf29.setBackground(new java.awt.Color(255, 102, 153));
        tf29.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf29.setText(" ");

        tf37.setBackground(new java.awt.Color(255, 102, 153));
        tf37.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf37.setText(" ");

        tf38.setBackground(new java.awt.Color(255, 102, 153));
        tf38.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf38.setText(" ");

        tf39.setBackground(new java.awt.Color(255, 102, 153));
        tf39.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf39.setText(" ");

        tf41.setBackground(new java.awt.Color(204, 0, 204));
        tf41.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf41.setText(" ");

        tf42.setBackground(new java.awt.Color(204, 0, 204));
        tf42.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf42.setText(" ");

        tf43.setBackground(new java.awt.Color(204, 0, 204));
        tf43.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf43.setText(" ");

        tf44.setBackground(new java.awt.Color(255, 204, 51));
        tf44.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf44.setText(" ");

        tf45.setBackground(new java.awt.Color(255, 204, 51));
        tf45.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf45.setText(" ");

        tf46.setBackground(new java.awt.Color(255, 204, 51));
        tf46.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf46.setText(" ");

        tf47.setBackground(new java.awt.Color(204, 204, 204));
        tf47.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf47.setText(" ");

        tf48.setBackground(new java.awt.Color(204, 204, 204));
        tf48.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf48.setText(" ");

        tf49.setBackground(new java.awt.Color(204, 204, 204));
        tf49.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf49.setText(" ");

        tf51.setBackground(new java.awt.Color(204, 0, 204));
        tf51.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf51.setText(" ");

        tf52.setBackground(new java.awt.Color(204, 0, 204));
        tf52.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf52.setText(" ");

        tf53.setBackground(new java.awt.Color(204, 0, 204));
        tf53.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf53.setText(" ");

        tf54.setBackground(new java.awt.Color(255, 204, 51));
        tf54.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf54.setText(" ");

        tf55.setBackground(new java.awt.Color(255, 204, 51));
        tf55.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf55.setText(" ");

        tf56.setBackground(new java.awt.Color(255, 204, 51));
        tf56.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf56.setText(" ");

        tf57.setBackground(new java.awt.Color(204, 204, 204));
        tf57.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf57.setText(" ");

        tf58.setBackground(new java.awt.Color(204, 204, 204));
        tf58.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf58.setText(" ");

        tf59.setBackground(new java.awt.Color(204, 204, 204));
        tf59.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf59.setText(" ");

        tf61.setBackground(new java.awt.Color(204, 0, 204));
        tf61.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf61.setText(" ");

        tf62.setBackground(new java.awt.Color(204, 0, 204));
        tf62.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf62.setText(" ");

        tf63.setBackground(new java.awt.Color(204, 0, 204));
        tf63.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf63.setText(" ");

        tf64.setBackground(new java.awt.Color(255, 204, 51));
        tf64.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf64.setText(" ");

        tf65.setBackground(new java.awt.Color(255, 204, 51));
        tf65.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf65.setText(" ");

        tf66.setBackground(new java.awt.Color(255, 204, 51));
        tf66.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf66.setText(" ");

        tf67.setBackground(new java.awt.Color(204, 204, 204));
        tf67.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf67.setText(" ");

        tf68.setBackground(new java.awt.Color(204, 204, 204));
        tf68.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf68.setText(" ");

        tf69.setBackground(new java.awt.Color(204, 204, 204));
        tf69.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf69.setText(" ");

        tf71.setBackground(new java.awt.Color(0, 102, 153));
        tf71.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf71.setText(" ");

        tf72.setBackground(new java.awt.Color(0, 102, 153));
        tf72.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf72.setText(" ");

        tf73.setBackground(new java.awt.Color(0, 102, 153));
        tf73.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf73.setText(" ");

        tf74.setBackground(new java.awt.Color(163, 154, 69));
        tf74.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf74.setText(" ");

        tf75.setBackground(new java.awt.Color(163, 154, 69));
        tf75.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf75.setText(" ");

        tf76.setBackground(new java.awt.Color(163, 154, 69));
        tf76.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf76.setText(" ");

        tf77.setBackground(new java.awt.Color(255, 0, 51));
        tf77.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf77.setText(" ");

        tf78.setBackground(new java.awt.Color(255, 0, 51));
        tf78.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf78.setText(" ");

        tf79.setBackground(new java.awt.Color(255, 0, 51));
        tf79.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf79.setText(" ");

        tf81.setBackground(new java.awt.Color(0, 102, 153));
        tf81.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf81.setText(" ");

        tf82.setBackground(new java.awt.Color(0, 102, 153));
        tf82.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf82.setText(" ");

        tf83.setBackground(new java.awt.Color(0, 102, 153));
        tf83.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf83.setText(" ");

        tf84.setBackground(new java.awt.Color(163, 154, 69));
        tf84.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf84.setText(" ");

        tf85.setBackground(new java.awt.Color(163, 154, 69));
        tf85.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf85.setText(" ");

        tf86.setBackground(new java.awt.Color(163, 154, 69));
        tf86.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf86.setText(" ");

        tf87.setBackground(new java.awt.Color(255, 0, 51));
        tf87.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf87.setText(" ");

        tf88.setBackground(new java.awt.Color(255, 0, 51));
        tf88.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf88.setText(" ");

        tf89.setBackground(new java.awt.Color(255, 0, 51));
        tf89.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf89.setText(" ");

        tf91.setBackground(new java.awt.Color(0, 102, 153));
        tf91.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf91.setText(" ");

        tf92.setBackground(new java.awt.Color(0, 102, 153));
        tf92.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf92.setText(" ");

        tf93.setBackground(new java.awt.Color(0, 102, 153));
        tf93.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf93.setText(" ");

        tf94.setBackground(new java.awt.Color(163, 154, 69));
        tf94.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf94.setText(" ");

        tf95.setBackground(new java.awt.Color(163, 154, 69));
        tf95.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf95.setText(" ");

        tf96.setBackground(new java.awt.Color(163, 154, 69));
        tf96.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf96.setText(" ");

        tf97.setBackground(new java.awt.Color(255, 0, 51));
        tf97.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf97.setText(" ");

        tf98.setBackground(new java.awt.Color(255, 0, 51));
        tf98.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf98.setText(" ");

        tf99.setBackground(new java.awt.Color(255, 0, 51));
        tf99.setFont(new java.awt.Font("Tahoma", 0, 18));
        tf99.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf26, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf27, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf28, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf29, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf31, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf32, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf33, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf34, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf35, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf36, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf37, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf38, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf39, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf41, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf42, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf43, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf44, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf45, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf46, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf47, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf48, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf49, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf51, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf52, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf53, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf54, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf55, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf56, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf57, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf58, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf59, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf61, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf62, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf63, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf64, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf65, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf66, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf67, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf68, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf69, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf71, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf72, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf73, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf74, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf75, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf76, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf77, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf78, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf79, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf81, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf82, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf83, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf84, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf85, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf86, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf87, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf88, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf89, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf91, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf92, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf93, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf94, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf95, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf96, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf97, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf98, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf99, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf69, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf79, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf89, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf91, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf92, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf93, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf94, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf95, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf96, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf97, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf98, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf99, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField tf11;
    private javax.swing.JTextField tf12;
    private javax.swing.JTextField tf13;
    private javax.swing.JTextField tf14;
    private javax.swing.JTextField tf15;
    private javax.swing.JTextField tf16;
    private javax.swing.JTextField tf17;
    private javax.swing.JTextField tf18;
    private javax.swing.JTextField tf19;
    private javax.swing.JTextField tf21;
    private javax.swing.JTextField tf22;
    private javax.swing.JTextField tf23;
    private javax.swing.JTextField tf24;
    private javax.swing.JTextField tf25;
    private javax.swing.JTextField tf26;
    private javax.swing.JTextField tf27;
    private javax.swing.JTextField tf28;
    private javax.swing.JTextField tf29;
    private javax.swing.JTextField tf31;
    private javax.swing.JTextField tf32;
    private javax.swing.JTextField tf33;
    private javax.swing.JTextField tf34;
    private javax.swing.JTextField tf35;
    private javax.swing.JTextField tf36;
    private javax.swing.JTextField tf37;
    private javax.swing.JTextField tf38;
    private javax.swing.JTextField tf39;
    private javax.swing.JTextField tf41;
    private javax.swing.JTextField tf42;
    private javax.swing.JTextField tf43;
    private javax.swing.JTextField tf44;
    private javax.swing.JTextField tf45;
    private javax.swing.JTextField tf46;
    private javax.swing.JTextField tf47;
    private javax.swing.JTextField tf48;
    private javax.swing.JTextField tf49;
    private javax.swing.JTextField tf51;
    private javax.swing.JTextField tf52;
    private javax.swing.JTextField tf53;
    private javax.swing.JTextField tf54;
    private javax.swing.JTextField tf55;
    private javax.swing.JTextField tf56;
    private javax.swing.JTextField tf57;
    private javax.swing.JTextField tf58;
    private javax.swing.JTextField tf59;
    private javax.swing.JTextField tf61;
    private javax.swing.JTextField tf62;
    private javax.swing.JTextField tf63;
    private javax.swing.JTextField tf64;
    private javax.swing.JTextField tf65;
    private javax.swing.JTextField tf66;
    private javax.swing.JTextField tf67;
    private javax.swing.JTextField tf68;
    private javax.swing.JTextField tf69;
    private javax.swing.JTextField tf71;
    private javax.swing.JTextField tf72;
    private javax.swing.JTextField tf73;
    private javax.swing.JTextField tf74;
    private javax.swing.JTextField tf75;
    private javax.swing.JTextField tf76;
    private javax.swing.JTextField tf77;
    private javax.swing.JTextField tf78;
    private javax.swing.JTextField tf79;
    private javax.swing.JTextField tf81;
    private javax.swing.JTextField tf82;
    private javax.swing.JTextField tf83;
    private javax.swing.JTextField tf84;
    private javax.swing.JTextField tf85;
    private javax.swing.JTextField tf86;
    private javax.swing.JTextField tf87;
    private javax.swing.JTextField tf88;
    private javax.swing.JTextField tf89;
    private javax.swing.JTextField tf91;
    private javax.swing.JTextField tf92;
    private javax.swing.JTextField tf93;
    private javax.swing.JTextField tf94;
    private javax.swing.JTextField tf95;
    private javax.swing.JTextField tf96;
    private javax.swing.JTextField tf97;
    private javax.swing.JTextField tf98;
    private javax.swing.JTextField tf99;
    // End of variables declaration//GEN-END:variables
    
}
